package ua.nau.edu.Enum;

/**
 * Created by root on 11/10/15.
 */
public enum EnumSharedPreferences {
    APP_PREFERENCES,
    SIGNED_IN_KEY,
    PROFILE_PHOTO_LOCATION_KEY,
    JUST_SIGNED_KEY,
    FIRST_LAUNCH,
    CORP_ID_KEY,
    CORP_LABEL_KEY,
    TOKEN_KEY,
    UNIQUE_ID,
    EXIT,
    ACCOUNTHEADER_BG_IMAGE,
    MAP_LAYER_KEY,
    MAP_MY_LOCATION_VISIBILITY_KEY,
    VK_PREFERENCES,
    VK_INFO_KEY,
    PROFILE_PHOTO_URL_KEY,
    VK_EMAIL_KEY,
    VK_SIGNED_KEY,
    VK_ID_KEY,
}
